[build]
  Command = "yarn build"
  Functions = "functions"
  Publish = "public"

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  conditions = { Language = ["en"] }

[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/projects/creopack/"
  to = "/fr/projets/"
  status = 301
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/projects/creopack/"
  to = "/en/projets/"
  status = 301
  conditions = { Language = ["en"] }

[[redirects]]
  from = "/projects/urbania/"
  to = "/fr/projets/"
  status = 301
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/projects/urbania/"
  to = "/en/projets/"
  status = 301
  conditions = { Language = ["en"] }

[[redirects]]
  from = "/projects/normal/"
  to = "/fr/projets/"
  status = 301
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/projects/normal/"
  to = "/en/projets/"
  status = 301
  conditions = { Language = ["en"] }

[[redirects]]
  from = "/projects/greysparrow/"
  to = "/fr/projets/"
  status = 301
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/projects/greysparrow/"
  to = "/en/projets/"
  status = 301
  conditions = { Language = ["en"] }

[[redirects]]
  from = "/projects/illustration-quebec/"
  to = "/fr/projets/"
  status = 301
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/projects/illustration-quebec/"
  to = "/en/projets/"
  status = 301
  conditions = { Language = ["en"] }

[[redirects]]
  from = "/projects/attraction-media/"
  to = "/fr/projets/"
  status = 301
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/projects/attraction-media/"
  to = "/en/projets/"
  status = 301
  conditions = { Language = ["en"] }

[[redirects]]
  from = "/projects/ici-artv/"
  to = "/fr/projets/"
  status = 301
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/projects/ici-artv/"
  to = "/en/projets/"
  status = 301
  conditions = { Language = ["en"] }

