[build]
  Command = "yarn build"
  Functions = "functions"
  Publish = "public"

[[redirects]]
  from = "/"
  to = "/en-usa"
  status = 302
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  conditions = { Language = ["en"] }